title: Bluto docs
description: >-
  CSS documentation for Bluto's webapp
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://docs.bluto.co.uk"

# permalinks config
permalink: /:path
collections:
  documentation:
    output: true
    permalink: /documentation/:path
  common:
    output: true
    permalink: /common/:path
  components:
    output: true
    permalink: /components/:path

# Build settings
plugins:
  - jekyll-feed
# sass
sass:
  sass_dir: assets/_sass
  style: compressed
# compress
# http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
