# Welcome to Jekyll!
title: Bluto documentation
description: >-
  CSS documentation for Bluto's webapp
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://docs.bluto.co.uk"

# Build settings
plugins:
  - jekyll-autoprefixer
  - jekyll-coffeescript
  - jekyll-inline-svg
# autoprefixer (for css)
autoprefixer:
  browsers:
  - last 10 versions
# sass
sass:
  sass_dir: assets/_sass
  style: compressed
# compress
# http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []
# svg
svg:
  optimize: true

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
