title: Bluto design
description: >-
  Bluto's design system documentation
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bluteau-ltd.github.io/bluto-design"

# permalinks config
permalink: /:path
collections:
  documentation:
    output: true
    permalink: /documentation/:path
    order:
      - tech-stack.md
      - conventions.md
      - file-structure.md
  utils:
    output: true
    permalink: /utils/:path
    order:
      - variables.md
      - mixins.md
      - global.md
      - colours.md
  components:
    output: true
    permalink: /components/:path

# plugins
plugins:
  - jekyll-inline-svg
# svg
svg:
  optimize: true
# sass
sass:
  sass_dir: assets/_sass
  style: compressed
# compress
# http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
